import Auth from "./auth/auth.js";
import * as assets from "./assets.js";
import { wrapError, lst } from "./assets.js";
import Social from "./auth/social.js";
import type Xbox from "./auth/xbox.js";
import type Minecraft from "./auth/minecraft.js";
import { fromToken, fromMclcToken, validate, MCToken } from "./auth/minecraft.js";
export const mcTokenToolbox = { fromToken, fromMclcToken, validate };
export default { Social, Auth, assets, wrapError, lst,mcTokenToolbox };
export type { Xbox, Minecraft, MCToken };
